name: Full Test Suite

# Comprehensive testing on PRs and pushes with .go changes
# Goal: <15 minutes for thorough validation
# Pure shell commands - no JavaScript actions (act_runner k8s has no Node.js)

on:
  pull_request:
    branches: [dev, main]
  workflow_dispatch:
  push:
    branches: [dev, main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - '.gitea/workflows/full-test.yml'

jobs:
  verify-and-test:
    name: Code Quality & Unit Tests
    runs-on: golang
    steps:
      - name: Install build deps
        run: apt-get update -qq && apt-get install -y -qq make bc

      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Install dependencies
        run: |
          go mod download
          make install-tools

      - name: Run verification (fmt, vet, lint)
        run: make verify

      - name: Run unit tests
        run: make test

      - name: Generate coverage report
        run: make test-coverage

      - name: Check coverage threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Coverage: ${COVERAGE}%"

          if (( $(echo "$COVERAGE < 65" | bc -l) )); then
            echo "::error::Coverage ${COVERAGE}% is below 65% threshold"
            exit 1
          fi

          echo "::notice::Coverage ${COVERAGE}% meets 65% threshold"

  sanity-tests:
    name: CSI Sanity Tests
    runs-on: golang
    steps:
      - name: Install build deps
        run: apt-get update -qq && apt-get install -y -qq make

      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Install dependencies
        run: go mod download

      - name: Run CSI sanity tests
        run: |
          echo "Running CSI sanity tests with 15 minute timeout..."
          go test -v -race -timeout 15m ./test/sanity/... 2>&1 | tee sanity-output.log
        continue-on-error: true
        id: sanity

      - name: Check sanity test result
        if: steps.sanity.outcome == 'failure'
        run: |
          echo "CSI sanity tests failed - see logs above"
          exit 1

  e2e-tests:
    name: E2E Tests
    runs-on: golang
    steps:
      - name: Install build deps
        run: apt-get update -qq && apt-get install -y -qq make

      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Run E2E tests
        run: make e2e-test

  mock-stress-tests:
    name: Mock RDS Stress Tests
    runs-on: golang
    steps:
      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Run mock stress tests
        run: |
          echo "Running concurrent stress tests..."
          go test -v -race -timeout 5m ./test/mock/... -run TestConcurrent
          echo "Mock stress tests passed"

  test-summary:
    name: Test Summary
    runs-on: golang
    needs: [verify-and-test, sanity-tests, e2e-tests, mock-stress-tests]
    if: always()
    steps:
      - name: Generate summary
        run: |
          echo "Test Results Summary"
          echo ""
          echo "| Test Suite | Status |"
          echo "|------------|--------|"
          echo "| Code Quality & Unit Tests | ${{ needs.verify-and-test.result }} |"
          echo "| CSI Sanity Tests | ${{ needs.sanity-tests.result }} |"
          echo "| E2E Tests | ${{ needs.e2e-tests.result }} |"
          echo "| Mock Stress Tests | ${{ needs.mock-stress-tests.result }} |"
          echo ""

          if [ "${{ needs.verify-and-test.result }}" = "success" ] && \
             [ "${{ needs.sanity-tests.result }}" = "success" ] && \
             [ "${{ needs.e2e-tests.result }}" = "success" ] && \
             [ "${{ needs.mock-stress-tests.result }}" = "success" ]; then
            echo "All tests passed! Ready for review."
            exit 0
          else
            echo "Some tests failed. Please review the logs."
            exit 1
          fi
