name: Quick Build

# Fast build on push to main branches - NO TESTS
# Goal: <2 minutes for rapid feedback
# Pure shell commands - no JavaScript actions (act_runner k8s has no Node.js)

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.planning/**'
      - '.github/**'

env:
  REGISTRY: git.whiskey.works
  IMAGE_NAME: whiskey/rds-csi

jobs:
  quick-build:
    name: Build Binary Only (Fast)
    runs-on: golang
    steps:
      - name: Install build deps
        run: apt-get update -qq && apt-get install -y -qq make

      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          git clone --depth=1 --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Verify build environment
        run: |
          go version
          make --version
          echo "Build environment ready"

      - name: Build binary
        run: make build-local

      - name: Verify binary
        run: |
          ls -lh bin/
          ./bin/rds-csi-plugin-* --version || true
          echo "Binary built successfully"

      - name: Build summary
        run: |
          echo "Quick build complete!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          ls -lh bin/ | grep rds-csi-plugin
