name: Quick Build

# Fast build on push to main branches - NO TESTS
# Goal: <5 minutes for rapid feedback

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.planning/**'
      - '.github/**'

env:
  # Update these for your Gitea registry
  REGISTRY: git.whiskey.works  # or use Gitea's built-in registry
  IMAGE_NAME: whiskey/rds-csi

jobs:
  quick-build:
    name: Build Binary and Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: make build-local

      - name: Quick smoke test
        run: |
          # Just verify the binary was built and runs
          ./bin/rds-csi-plugin-* --version || true
          echo "✅ Binary built successfully"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Uncomment when ready to push to registry
      # - name: Log in to registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ secrets.REGISTRY_USER }}
      #     password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push multi-arch container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false  # Set to true when registry is configured
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_TAG=${{ github.ref_name }}-${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build summary
        run: |
          echo "✅ Quick multi-arch build complete!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Platforms: linux/amd64, linux/arm64"
          echo ""
          echo "Container tags:"
          echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
          echo "  - ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}"
          echo ""
          echo "To enable push: Set 'push: true' in workflow and uncomment login step"
