name: Quick Build

# Fast build on push to main branches - NO TESTS
# Goal: <5 minutes for rapid feedback

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.planning/**'
      - '.github/**'

env:
  # Update these for your Gitea registry
  REGISTRY: git.whiskey.works  # or use Gitea's built-in registry
  IMAGE_NAME: whiskey/rds-csi

jobs:
  quick-build:
    name: Build Binary and Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: make build-local

      - name: Quick smoke test
        run: |
          # Just verify the binary was built and runs
          ./bin/rds-csi-plugin-* --version || true
          echo "✅ Binary built successfully"

      - name: Build container
        run: |
          docker build \
            --build-arg GIT_COMMIT=${{ github.sha }} \
            --build-arg GIT_TAG=${{ github.ref_name }}-${{ github.sha }} \
            --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }} \
            .

      # Uncomment when ready to push to registry
      # - name: Log in to registry
      #   run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      # - name: Push container
      #   run: |
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
      #     docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}

      - name: Build summary
        run: |
          echo "✅ Quick build complete!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo ""
          echo "Container tag: ${{ github.ref_name }}-${{ github.sha }}"
