name: Quick Build

# Fast build on push to main branches - NO TESTS, NO GITHUB ACTIONS
# Goal: <2 minutes for rapid feedback
# Uses direct commands instead of GitHub actions to avoid slow cloning

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.planning/**'
      - '.github/**'

env:
  REGISTRY: git.whiskey.works
  IMAGE_NAME: whiskey/rds-csi

jobs:
  quick-build:
    name: Build Binary Only (Fast)
    runs-on: ubuntu-latest  # golang:1.22-bookworm
    steps:
      - name: Debug workspace
        run: |
          echo "Working directory: $(pwd)"
          echo "Files in workspace:"
          ls -la
          echo ""
          echo "Looking for go.mod:"
          ls -la go.mod || echo "❌ go.mod not found!"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Go installation
        run: |
          go version
          echo "✅ Go is pre-installed in golang:1.22-bookworm"

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: make build-local

      - name: Verify binary
        run: |
          ls -lh bin/
          ./bin/rds-csi-plugin-* --version || true
          echo "✅ Binary built successfully"

      - name: Build summary
        run: |
          echo "✅ Quick build complete!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo ""
          echo "Built binary:"
          ls -lh bin/ | grep rds-csi-plugin
