name: Release

# Full test suite + build for tagged releases
# Triggered by tag push or manual dispatch
# Pure shell commands - no JavaScript actions (act_runner k8s has no Node.js)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v0.10.3)'
        required: true
        type: string

env:
  REGISTRY: git.whiskey.works
  IMAGE_NAME: whiskey/rds-csi

jobs:
  full-test:
    name: Run Full Test Suite
    runs-on: golang
    steps:
      - name: Install build deps
        run: apt-get update -qq && apt-get install -y -qq make bc

      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            git clone --branch ${{ github.event.inputs.tag }} ${{ github.server_url }}/${{ github.repository }}.git .
          else
            git clone ${{ github.server_url }}/${{ github.repository }}.git .
            git checkout ${{ github.sha }}
          fi

      - name: Install dependencies
        run: |
          go mod download
          make install-tools

      - name: Run all tests
        run: |
          echo "Running verification..."
          make verify

          echo "Running unit tests..."
          make test

          echo "Running sanity tests..."
          go test -v -race -timeout 15m ./test/sanity/...

          echo "Running stress tests..."
          go test -v -race -timeout 5m ./test/mock/... -run TestConcurrent

          echo "All tests passed"

      - name: Check coverage
        run: |
          make test-coverage
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Coverage: ${COVERAGE}%"

          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Coverage ${COVERAGE}% is below 60% threshold"
            exit 1
          fi

  build-release:
    name: Build Release Binary
    runs-on: golang
    needs: full-test
    steps:
      - name: Install build deps
        run: apt-get update -qq && apt-get install -y -qq make

      - name: Checkout code
        run: |
          git config --global credential.helper store
          echo "https://token:${{ github.token }}@$(echo '${{ github.server_url }}' | sed 's|https\?://||')" > ~/.git-credentials
          git clone ${{ github.server_url }}/${{ github.repository }}.git .
          git fetch --tags
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            git checkout ${{ github.event.inputs.tag }}
          else
            git checkout ${{ github.sha }}
          fi

      - name: Get version info
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.tag }}"
          else
            VERSION="${{ github.ref_name }}"
          fi

          GIT_COMMIT=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "commit=${GIT_COMMIT}" >> $GITHUB_OUTPUT
          echo "date=${BUILD_DATE}" >> $GITHUB_OUTPUT

          echo "Building release ${VERSION} (commit: ${GIT_COMMIT})"

      - name: Build release binaries
        run: |
          make build-all
          echo "Release binaries built"
          ls -lh bin/

      - name: Create release notes
        run: |
          VERSION=${{ steps.version.outputs.version }}
          PREV_TAG=$(git describe --tags --abbrev=0 ${VERSION}^ 2>/dev/null || echo "")

          cat > release-notes.md <<EOF
          ## Release ${VERSION}

          **Built:** ${{ steps.version.outputs.date }}
          **Commit:** ${{ steps.version.outputs.commit }}

          **Platforms:** linux/amd64, linux/arm64
          EOF

          if [ -n "$PREV_TAG" ]; then
            echo "" >> release-notes.md
            echo "### Changes since ${PREV_TAG}" >> release-notes.md
            echo "" >> release-notes.md
            git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%an)" --no-merges >> release-notes.md
          fi

          echo "--- Release Notes ---"
          cat release-notes.md

      - name: Release summary
        run: |
          echo "Release ${{ steps.version.outputs.version }}"
          echo ""
          echo "Tests passed"
          echo "Binaries built"
          ls -lh bin/
