---
# StorageClass for RDS CSI Driver
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rds-nvme
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"

# Provisioner name matches the CSI driver name
provisioner: rds.csi.srvlab.io

# Parameters passed to CreateVolume
parameters:
  # Filesystem type (ext4, ext3, xfs)
  csi.storage.k8s.io/fstype: ext4

  # NVMe/TCP target address (high-speed storage interface)
  nvmeAddress: "10.42.68.1"

  # NVMe/TCP port (default: 4420)
  nvmePort: "4420"

  # Volume base path on RDS
  volumePath: "/storage-pool/metal-csi"

# Volume binding mode
volumeBindingMode: Immediate

# Reclaim policy: Delete volumes when PVC is deleted
reclaimPolicy: Delete

# Allow volume expansion (requires ExpandVolume implementation)
allowVolumeExpansion: false

# Mount options (optional)
# mountOptions:
#   - noatime
#   - nodiratime
